project_id = "youjypiuqxlvyizlszmd"

[functions.process-policies-ai]
import_map = "./functions/_shared/import_map.json"

[functions.start-policy-analysis]
import_map = "./functions/_shared/import_map.json"