// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://youjypiuqxlvyizlszmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdWp5cGl1cXhsdnlpemxzem1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNjE2NjQsImV4cCI6MjA2NjczNzY2NH0.Z2pTJ_bPOEm8578lBx8qMzsA1pyNBpuuvb4jmibDPcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);